### ISSUE TITLE
Add all Hadolint rules

### ISSUE THREAD

**Issue by Sancretor** [cnescatlab/sonar-hadolint-plugin#1]
#### Is your feature request related to a problem? Please describe.**
> The plugin only implements one hadolint rule, and we need all of them to be integrated.

#### Describe the solution you'd like
> Add all the remaining rules inside the XML file that describes them.

#### Describe alternatives you've considered
> No alternatives.

#### Additional context
> Only one rule was implemented for testing purposes during first development phase. now that the plugin is working, we should add them all.

**Comment by Sancretor** [comment]
Hi @JohannesBe 

I already started working on this on a dedicated branch, if you are interested : https://github.com/cnescatlab/sonar-hadolint-plugin/tree/feature/add-hadolint-rules
 
I was focusing on the native DL rules, and was thinking, just like you, about checking licences to use what was done in the shellcheck plugin.

Sorry for the late responses, I'm on holidays...

**Comment by JohannesBe** [comment]
I wrote a shellscript to retrieve all `SC` rules and parse them into xml. This way we can easily re-run our script to sync with the shellcheck sonar repository periodically.

On the way I noticed that the shellcheck repository has tags for their rules. Therefore I created #6. 

```
#!/bin/bash
# shellcheck disable=SC2001

set -euxo pipefail

ORIG=$(pwd)
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

function cleanup() {
    rm -rf "/tmp/shellcheck" || true
    cd "$ORIG"
}

trap cleanup EXIT

cd "/tmp"
rm -rf "shellcheck"
git clone "https://github.com/sbaudoin/sonar-shellcheck.git" "shellcheck"
cd "shellcheck"

set +x
FILES=$(find "src/" | grep -E '.*/SC[0-9]+\.json' | sort)

rm -rf blobs.json
touch blobs.json

for FILE in $FILES
do
    KEY=$(sed 's/.*\(SC[0-9]\+\)\.json/\1/g' <<< "$FILE")
    jq -c '{rule:{key:"'"$KEY"'",name:.title,description:.title,type:.type,remediationFunction:.remediation.func|ascii_upcase|sub("[^A-Z0-9]";"_"),remediationFunctionBaseEffort:.remediation.constantCost,status:.status,tags:{tag:.tags},cardinality:"SINGLE"}}' "$FILE" >> blobs.json
    echo -n "$KEY,"
done
echo ""
set -x

jq -s '{"hadolint-rules":.}' < blobs.json > full.json
npm i json2xml-cli .
./node_modules/json2xml-cli/src/json2xml.js -i full.json --header -o "/tmp/shellcheck/out.xml"

xmllint --format "/tmp/shellcheck/out.xml" > "$DIR/shellcheck.xml"
set +x
echo "------------------------------------------------------------------------------------"
echo "|                                                                                  |"
echo "| [SUCCESS]                                                                        |"
echo "| Conversion successful! File can be found at:                                     |"
echo -n "| " && printf "%-80s" "$DIR/shellcheck.xml" && echo " |"
echo "|                                                                                  |"
echo "------------------------------------------------------------------------------------"
```

Output:
[shellcheck.xml.txt](https://github.com/cnescatlab/sonar-hadolint-plugin/files/5117807/shellcheck.xml.txt)

**Comment by JohannesBe** [comment]
Some comments:

- Finding a good json -> xml conversion tool proved to be a rabbit-hole. In the end I settled with a kind-of small node.js library called `json2xml-cli`, but I'm kind of not happy randomly installing node-js libraries.
- The script requires the `jq` dependency, a well-established CLI tool for parsing JSON. I use this one to pre-parse the JSON into a useful format for the xml conversion tool.
- The shellcheck sonarqube extension does not have a distinction between `name` and `description`, for now I just copied their `title` field into both. Is this okay for us?

**Comment by JohannesBe** [comment]
There is still a bug in the shell script I think, the `<status></status>` should be upper case. I think instead of
```
    jq -c '{rule:{key:"'"$KEY"'",name:.title,description:.title,type:.type,remediationFunction:.remediation.func|ascii_upcase|sub("[^A-Z0-9]";"_"),remediationFunctionBaseEffort:.remediation.constantCost,status:.status,tags:{tag:.tags},cardinality:"SINGLE"}}' "$FILE" >> blobs.json
```
the following should work:
```
    jq -c '{rule:{key:"'"$KEY"'",name:.title,description:.title,type:.type,remediationFunction:.remediation.func|ascii_upcase|sub("[^A-Z0-9]";"_"),remediationFunctionBaseEffort:.remediation.constantCost,status:.status|ascii_upcase,tags:{tag:.tags},cardinality:"SINGLE"}}' "$FILE" >> blobs.json
```

**Comment by JohannesBe** [comment]
There is also another bug regarding `&amp;amp;` for some rules, I will check if I can devise a fix for this soon™

**Comment by Sancretor** [comment]
Hi @JohannesBe 

Again, having a script to automatically retrieve Shellcheck rules is a great idea ! Thank you !
Just like you, having a node.js script with dependencies is not what I would have liked... but good converters are not easy to find, I agree.
Hopefully, we would not run it too often, so could be ok for a start.
