### ISSUE TITLE
Dockerfiles are not linked to the Dockerfile language in SonarQube

### ISSUE THREAD

**Issue by Sancretor** [cnescatlab/sonar-hadolint-plugin#2]
#### Describe the bug
When you run an analysis with SonarScanner, the Dockerfiles in the project can be seen in the "code" menu on SonarQube, but they are linked to the "Unknown" language instead of the Dockerfile one.  
This is due to Dockerfile not having standardized file extension, and SonarQube only working with file extension to identify files.

#### To reproduce
1. Have a project with a Dockerfile
2. Configure the analysis as described on the README
3. Analyze your project with SonarScanner or else
4. Go to SonarQube web interface, into your project "code" page

#### Expected behavior
SonarQube should identify the Dockerfiles are being linked to the Dockerfile language.

#### Screenshots & log
None.

#### User environment
 - OS: Debian 10
 - SonarQube version : 7.9.3
 - Java version: 1.11
 - Hadolint version: 1.18.0
 - Plugin version: dev

#### Additional context
None.

**Comment by JohannesBe** [comment]
This is kind of a nasty one I think, since Dockerfile's do not have an extension by default, we are kind of unable to do define the language properly.

Maybe we can use `Dockerfile` as a default, and extend it with the files as listed in the `sonar.hadolint.dockerfiles.path` property if it is specified? E.g.:
- `sonar.hadolint.dockerfiles.path` is not set => `Dockerfile` as suffix
- `sonar.hadolint.dockerfiles.path` is set (example value: `deploy/docker/Dockerfile.backend,deploy/docker/Dockerfile.redis,deploy/docker/Dockerfile.app,deploy/docker/Dockerfile.control-panel`)
   => `['Dockerfile', 'Dockerfile.backend', 'Dockerfile.redis', 'Dockerfile.app', 'Dockerfile.control-panel']`

**Comment by JohannesBe** [comment]
Something similar to https://github.com/SonarSource/sonar-java/blob/7665e51c2eeaf7525fdae06bc278d759df63215c/sonar-java-plugin/src/main/java/org/sonar/plugins/java/Java.java#L85, except that we split the path strings off and only retain the file names?

Or is this property not available at the time of language definition?

**Comment by Sancretor** [comment]
Hi @JohannesBe 

Yes, this is THE nasty one...
By default, we are only looking for the `Dockerfile` file and this could be entirely overridden by the `sonar.hadolint.dockerfiles.path` property.
If the user is setting values for this property, I feel like we should not add `Dockerfile` in it as this file might not exist.

Unfortunately, the getFileSuffixes method is used to define the language when SonarQube server deploys the plugin so... no, the property is not available at this time.

My first idea was to look for an interface/method to manually link a file to the language in Sensor context, when we compute metrics/highlightings/issues. I cannot find anything helpful for the moment.

**Comment by JohannesBe** [comment]
Hi @Sancretor , 
I was about to open an issue in the sonarqube community, but I see that you have already done so :) 
Linking for future reference:
https://community.sonarsource.com/t/link-a-file-with-no-extension-to-an-existing-language/31146

**Comment by JohannesBe** [comment]
When looking through some older posts I came accross this one: https://community.sonarsource.com/t/support-for-dockerfiles/19078

It seems that you can use glob patterns for the file suffix property. Maybe we can use `**/Dockerfile*` or something?

**Comment by Sancretor** [comment]
Hi @JohannesBe 

Thanks, I totally forgot to mention it here !
Ok, so using the sonar-scanner property seems to be the way to do it, as both these links suggest to use it.
I'll try that when I have some time.

I understood someone else already did a sonar hadolint plugin, but still not available for the community ... that's sad.

**Comment by Sancretor** [comment]
Following my successful tests, I created a PR on this topic #11 
@JohannesBe Feel free to have a look at it, and tell what you think about how it works.
