### ISSUE TITLE
Does not work with maven mutimodule project

### ISSUE THREAD

**Issue by saeeda1981** [cnescatlab/sonar-hadolint-plugin#25]
I am not able to publish results of Docker lint along with regular results for maven multimodule project.  Sonar only publishes scan results for java modules and not the lint results for dockerfiles kept as docker/Dockerfile.* 

i am trying following which does not work 
mvn sonar:sonar -Dsonar.host.url=http://localhost:4950/  -Dsonar.lang.patterns.dockerfile=docker/Dockerfile.jdk11 -Dsonar.hadolint.reports.path=./hadolint/hadoscan_test-jdk11.xml

**Comment by Sancretor** [comment]
Hi @saeeda1981 

Thanks for your feedback !

From what I see, your Dockerfiles are not in src, and by defaut the maven sonar plugin only considers the src directory as source files.
Consequently, your docker directory is ignored by the sonar:sonar goal because it is not part what the sonar scanner would consider as sources.
You should have a look at this plugin to find how to add your docker directory as an additional location for sources.
Otherwise, use the Sonar Scanner CLI and you'll see the plugin works perfectly !

**Comment by saeeda1981** [comment]
> Hi @saeeda1981
> 
> Thanks for your feedback !
> 
> From what I see, your Dockerfiles are not in src, and by defaut the maven sonar plugin only considers the src directory as source files.
> Consequently, your docker directory is ignored by the sonar:sonar goal because it is not part what the sonar scanner would consider as sources.
> You should have a look at this plugin to find how to add your docker directory as an additional location for sources.
> Otherwise, use the Sonar Scanner CLI and you'll see the plugin works perfectly !

Hello @Sancretor .  Thanks for a prompt reply and this plugin itself :) 
You are right in saying that maven sonar plugin does not handle any additional directories well,  while I am able to do workaround for regular maven project (by adding sonar.sources=src/main/java,docker),  i am facing challenges with multimodule  projects as even when I am calculating correct module paths for all modules,  the docker folder does not appear in analysis.    On contrary, the MSBuild for Sonar plugin works well, and understands the sub-projects under parent solutions +  also considers my docker directory when I specify  sonar.sources=docker   .

**Comment by Sancretor** [comment]
Hi @saeeda1981 
I understand this is an issue related to the use of SonarScanner with Java multimodule project.
As this is not related to the plugin, I cannot help you much on this topic and will close this issue.
Thanks for your feedback !
