### ISSUE TITLE
Absolute report path for sonar.hadolint.reports.path

### ISSUE THREAD

**Issue by HammerNL89** [cnescatlab/sonar-hadolint-plugin#27]
#### Describe what you need to know
I use this plugin in an Azure DevOps pipeline. Before I run SQ I import the hadolint.xml report as a pipeline artifact. 

Structure: 
Base directory (build.sourcesdirectory) is /home/vsts/work/1/s
```
/home/vsts/work/1/s
total 16
-rw-r--r-- 1 vsts docker   59 Aug 24 14:43 Dockerfile
-rw-r--r-- 1 vsts docker  985 Aug 24 14:43 README.md
-rw-r--r-- 1 vsts docker 2873 Aug 24 14:43 azure-pipelines.yml
-rw-r--r-- 1 vsts docker  379 Aug 24 14:43 sonar-project.properties
```
Artifact is by default imported in: /home/vsts/work/1
```
/home/vsts/work/1
total 20
drwxr-xr-x 2 vsts docker 4096 Aug 24 14:43 a
drwxr-xr-x 2 vsts docker 4096 Aug 24 14:43 b
drwxr-xr-x 2 vsts docker 4096 Aug 24 14:43 hadolint_results
drwxr-xr-x 3 vsts docker 4096 Aug 24 14:43 s
```
For `sonar.hadolint.reports.path` I specified the absolute path `/home/vsts/work/1/hadolint_results/hadolint.xml` However this doesn't work, it only accepts `../hadolint_results/hadolint.xml`

For other plugins report paths I specify the absolute path without an issue. Is this working as intended? 

#### User environment 
 - SonarQube version 8.9.0.43852
 - Hadolint version: v2.6.1

**Comment by Sancretor** [comment]
Hi @HammerNL89 
Thanks for your feedback !
That's a weird error... I'll look into it as soon as possible.
