### ISSUE TITLE
Installation (building) instructions

### ISSUE THREAD

**Issue by JohannesBe** [cnescatlab/sonar-hadolint-plugin#5]
Hi @Sancretor ,

Since there are no jar releases for this package (as of right now), the following instruction is quite unclear:
> Install sonar-hadolint-plugin-*.jar in <SONARQUBE_HOME>/extensions/plugins/.

and requires manual building of the jar.

Maybe provide some instructions for this?
Not all sonarqube maintainers may be smart enough to know how to build a maven project.

Kind regards,

J.

**Comment by neeleshg** [comment]
I just run `mvn package` at root level of code.
It created JAR file as well.
However whenever I used `-Dsonar.hadolint.activated=true`  it throws error saying `java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0`

Have I created package appropriately ?

Regards
Neelesh

**Comment by Sancretor** [comment]
Hi @neeleshg 
I'm using the very same mvn command.
It might be caused by a missing mandatory parameter, I don't know.
As I said before, this is a work in progress project, so not intended to work yet.
