### ISSUE TITLE
Possibility to add tags to the rules.xml file

### ISSUE THREAD

**Issue by JohannesBe** [cnescatlab/sonar-hadolint-plugin#6]
SonarQube Tags are useful to quickly find what kind of issues need to be resolved.

**Comment by JohannesBe** [comment]
In the script from [this comment](https://github.com/cnescatlab/sonar-hadolint-plugin/issues/1#issuecomment-679099891), I implemented it with the following syntax:

```
<rule>
    <!-- ... -->
    <tags>
        <tag>Shell</tag>
        <tag>Dockerfile</tag>
    </tags>
</rule>
```

**Comment by Sancretor** [comment]
Hi @JohannesBe 

Adding tags is a good idea !
Rather than only indicating if it's a Dockerfile or Shell rule, I would add another tag to tell it's an Hadolint rule or a Shellcheck rule.
What do you think about it ?
